### ISSUE TITLE
Tutorial needs to be updated

### ISSUE THREAD

**Issue by dmth** [52North/sos-importer#14]
The tutorial how to import the code into eclipse https://wiki.52north.org/bin/view/SensorWeb/SosImporter#Import_Current_Trunk_in_Eclipse needs to be updated.

**Comment by EHJ-52n** [comment]
https://wiki.52north.org/bin/view/SensorWeb/SosImporter#How_to_Build
and
https://wiki.52north.org/bin/view/SensorWeb/SosImporter#Example_tutorial
should be updated.
The section about import trunk in eclipse is removed as the SVN is history.
