### ISSUE TITLE
Update user guide

### ISSUE THREAD

**Issue by johnjohndoe** [52North/sos-importer#31]
I am trying to follow the [user guide](http://52north.org/files/sensorweb/eo2h/52n-sensorweb-sos-importer-guide.pdf) available in the [example tutorial](https://wiki.52north.org/bin/view/SensorWeb/SosImporter#Example_tutorial) which seems to be outdated:

> SOS Importer 0.1.0, document revision 0.1, 2011-09-13

Therefore, I am not able to answer these questions showing up in the configuration file wizard:

* What is the Feature Of Interest for the marked measured value column?
* What is the Observed Property for the marked measured value column?
* What is the Unit Of Measurement for the marked measured value column?

If I accept the defaults and start the actual import process with the generated configuration file I end up with a program failure as reported in this [issue](https://github.com/52North/OX-Framework/issues/37#issuecomment-77361729).

---

It would probably a good idea to **provide a configuration file** with the demo data. This will enable beginners to run the demo import independent from understanding the importer.

**Comment by EHJ-52n** [comment]
I would expect a basic knowledge of SWE concepts if you want to use the importer. Hence, the questions you stated should be clear.

**Comment by CrazyJoeMalloy** [comment]
I've found that this article helps keep me on track with the concepts and terms when using the importer:
[http://www.ogcnetwork.net/sos_2_0/tutorial/om](http://www.ogcnetwork.net/sos_2_0/tutorial/om)

I find that using the core/wizard modules gives me the bones of what I need to use the feeder, but inevitably I need to modify the generated XML document to get things to work.  I've had no luck with generated resources, but manual ones work well enough.

I wonder if there's a cheatsheet of the XML configuration file elements and values for reference?  I've had to suss out what did what from comparing various generated versions.

**Comment by EHJ-52n** [comment]
@CrazyJoeMalloy: Thank you for the link to the OGC resource. I will add this to the sos-importer documentatin in our wiki.

In addition, your statement about the schema forces me to think about adding a special schema section.

* Do you have any special elements you need more input for?
* What about the comments in the [schema source code](https://github.com/52North/sos-importer/blob/develop/bindings/src/main/resources/import-configuration.xsd)?
* Are they detailed enough?

**Comment by CrazyJoeMalloy** [comment]
@EHJ-52n: Happy to help!

I have to admit, to my shame, that I was not familiar with the schema - I've been away from Java for a long time and have only rarely dug into XML schema files - also a newbie to Maven on top of that...so I'm more or less drowning in my own ignorance :)

The documentation in the schema is certainly helpful and in combination with a configuration file helps to address most of my needs and questions.  The generated resource sections of the XSD seem a little sparse on how they work, as I've said I've had no luck with them - but manual resources seem to work fine.

I'm curious on the nature of "IdRef" values - are they simply an internal value, local to the configuration and use of the feeder or are those values also passed into and used by the SOS?  They appear to have no play in the SOS, nothing is apparent in the SensorML.

**Comment by EHJ-52n** [comment]
@johnjohndoe @CrazyJoeMalloy 

I have updated the wiki topic and added the following sections:

* https://wiki.52north.org/bin/view/SensorWeb/SosImporter#Terminology
* https://wiki.52north.org/bin/view/SensorWeb/SosImporter#Configuration_Schema

**Comment by CrazyJoeMalloy** [comment]
@EHJ-52n 
Very nice!  Exactly the kind of information that I was looking for.  Thanks!
