### ISSUE TITLE
How many "Feature Of Interest" and "Observed Property" to create?

### ISSUE THREAD

**Issue by johnjohndoe** [52North/sos-importer#39]
Given the following property columns from a .csv file:

* sensor_id
* date
* partikelPM10Mittel
* partikelPM10Ueberschreitungen
* ...

![sos-importer-foi](https://cloud.githubusercontent.com/assets/144518/8291040/34f49434-1927-11e5-8dca-3d5d038e017c.png)

Do I have to create **one** or **two** "Feature Of Interest" for "partikelPM10Mittel" and "partikelPM10Ueberschreitungen"?

![sos-importer-op](https://cloud.githubusercontent.com/assets/144518/8291041/393f9b9c-1927-11e5-951c-798d3493741f.png)

Do I have to create **one** or **two** "Observed Property" for "partikelPM10Mittel" and "partikelPM10Ueberschreitungen"?

At the end of the wizard coordinates can be specified for each "Feature Of Interest" which tells me that I probably should use the **same** "Feature Of Interest" for "partikelPM10Mittel" and "partikelPM10Ueberschreitungen" since both refer to "partikel".

![sos-importer-position](https://cloud.githubusercontent.com/assets/144518/8291052/455d4244-1927-11e5-9bdc-b16472409707.png)

What I do not understand then: What is a "Sensor" in the meaning of the importer? I expected that it is the physical station which has multiple sensors and therefore latitude/longitude are defined once.

**Comment by johnjohndoe** [comment]
@EHJ-52n Any comment?

**Comment by EHJ-52n** [comment]
The number of features depends on your model. If all stations/sensors observe the same feature, you need only one, for example.

The sensor model of the import is currently not capable of hierarchical sensor systems, hence, a sensor is a single sensor instance, e.g. a thermometer of an weather station.
