### ISSUE TITLE
Always provide skip reason

### ISSUE THREAD

**Issue by johnjohndoe** [52North/sos-importer#42]
I am running the importer on a CSV file. All lines are skipped. The importer does **not** state the reason. Here is the console output:

```
[org.n52.sos.importer.feeder.task.OneTimeFeeder] TRACE SensorObservationService \
- 		Skip CSV line #2750: 124,2015-06-21,17.0,14.0,1.9,3.0,35.0,58.0,,,,,,,,
[org.n52.sos.importer.feeder.task.OneTimeFeeder] TRACE SensorObservationService \
- 		Skip CSV line #2751: 143,2015-06-21,11.0,18.0,,,27.0,62.0,,,,,,,,
```
The relevant code parts can be found [here](https://github.com/52North/sos-importer/blob/52n-sos-importer-0.4.0/feeder/src/main/java/org/n52/sos/importer/feeder/SensorObservationService.java#L309) and [here](https://github.com/52North/sos-importer/blob/52n-sos-importer-0.4.0/feeder/src/main/java/org/n52/sos/importer/feeder/SensorObservationService.java#L357). Please ensure a reason is always provided.

**Comment by nuest** [comment]
From the log statement it looks like this might be the line where the log actually comes from, because there is no "Raw data" section.

https://github.com/52North/sos-importer/blob/52n-sos-importer-0.4.0/feeder/src/main/java/org/n52/sos/importer/feeder/SensorObservationService.java#L478

**Comment by johnjohndoe** [comment]
It looks like as if lines are skipped in [`importData` on line 307](https://github.com/52North/sos-importer/blob/52n-sos-importer-0.4.0/feeder/src/main/java/org/n52/sos/importer/feeder/SensorObservationService.java#L307) the first time. Then when I run the importer again lines are skipped because they [have been processed before (see line 478)](https://github.com/52North/sos-importer/blob/52n-sos-importer-0.4.0/feeder/src/main/java/org/n52/sos/importer/feeder/SensorObservationService.java#L478).

**Comment by EHJ-52n** [comment]
Fixed in 74379980c26942b.

**Comment by johnjohndoe** [comment]
Skip reasons are still **not provided in all cases**. I am using the latest development version at commit d678a8b6cabb1b43a6c2ee2a8a0c9db6e2a87bb4 which integrates the fix you referred to in commit 74379980c26942bc48d7fae2ad3db18f5b2ce363.

**Comment by EHJ-52n** [comment]
Could you give some more details than
> **not provided in all cases**.

Thank you.

**Comment by johnjohndoe** [comment]
Please find the detailed description on how to reproduce the bug in issue #44. The log files of the 2nd run show the console output without a reason.

```
17:21:33.202 [org.n52.sos.importer.feeder.task.OneTimeFeeder] 
    TRACE SensorObservationService - 		Skip CSV line (3) #2: 
    888,2015-01-02,42.0,6,6,1,20.0,35.0,4.9,1.3,6,1,47.0,40.0,6,6
```
