### ISSUE TITLE
org.n52.oxf.OXFException: Could not parse response to XML.

### ISSUE THREAD

**Issue by agtokty** [52North/sos-importer#53]
Hi all,
I wonder if sos-importer work on only 52NorthSos server? Because when i trying to execute sos-impoerter, it gives me this error :  https://gist.github.com/agtokty/78644222c6720d8e8ada

is there something worng with my service or with OX-Framework ? 

Regards.

**Comment by EHJ-52n** [comment]
@agtokty Could you please tell me why you closed this issue?

**Comment by agtokty** [comment]
When sos importer sends getCapabilities post request to my sos server, its content type is 'text/xml; charset=iso-8859-1', but my sos service couldn't handle  this content type , it was supporting  only "text/xml" and "application/xml" content type of post requests. So, i changed my server to support 'text/xml; charset=iso-8859-1' content type post requests and issue resolved. I think it was my server issue not sos-importer issue.

**Comment by EHJ-52n** [comment]
Hi @agtokty,
thank you very much for clarifying this.
Have a nice day,
Eike
