### ISSUE TITLE
Missleading Typo in Wiki-documentation (Example Tutorial)

### ISSUE THREAD

**Issue by DanielScholten** [52North/sos-importer#55]
in the [Example Tutorial](https://wiki.52north.org/bin/view/SensorWeb/SosImporter#Example_tutorial), Step 5, the pattern is given as 'dd.mm.yyyy HH:mm', while it has to be 'dd.MM.yyyy HH:mm ' (compare the month-entry). With the wrong pattern, the feeder is not able to properly insert any observation.

By the way, you could add a hint in [How to build](https://wiki.52north.org/bin/view/SensorWeb/SosImporter#How_to_Build), Step 1, that a JDK is needed. For convenience, you could serve a ready-to-use config-file for the feeder in section [Demo data](https://wiki.52north.org/bin/view/SensorWeb/SosImporter#Demo_data)

Best wishes
Daniel

**Comment by johnjohndoe** [comment]
I also had a lot of trouble understanding how to use the importer.
As a side note: I created a little [screenshot tutorial](https://github.com/johnjohndoe/SOS-Importer-Blume) a while ago. It might be useful for you, although it is specific to the kind of data I worked with.

**Comment by EHJ-52n** [comment]
@DanielScholten 

Thank you very much for your very useful feedback. 1 and 2 are solved in the wikipage, now.  Regarding 3, I would like to remind you to put not to many bugs/issues in one github issue. See #56.
