### ISSUE TITLE
Bad srsName forging in insertObservation request

### ISSUE THREAD

**Issue by glegal** [52North/sos-importer#72]
When the sos-importer send an InsertObservation request, the srsName of the feature of interest is malformed : 
http://www.opengis.net/def/crs/EPSG/0/http://www.opengis.net/def/crs/EPSG/0/4326

The prefix is added twice.
I join the datafile, configuration file and an xml file containing the insertObservation request
[config-files.zip](https://github.com/52North/sos-importer/files/843959/config-files.zip)

**Comment by EHJ-52n** [comment]
Thanks for reporting this issue. I already fixed it in 52North/OX-Framework#54 and waiting for a review.
