### ISSUE TITLE
Transactional authorization token support

### ISSUE THREAD

**Issue by BWibo** [52North/sos-importer#80]
Hello everybody,

is there currently any way to use the SOS Importer with a SOS server, that is using a *transactional authorization token* to limit access to transactional operations? I could not find any documentation on this on Github or [here](https://wiki.52north.org/SensorWeb/SosImporter).

For instance, sending an `InsertSensor` request from an `XML` file to a token secured server from the shell using CURL works fine:
```bash 
curl -v \
       -H "Content-Type: application/soap+xml;charset=UTF-8" \
       -H "Authorization: IamTheSecretToken-c1db8eb9f3f7" \
       -X POST \
       -d @insertSensor-SOAP.xml \
     http://my.sos.server:8080/52n-sos-webapp/service > response.xml
```
However, is there any way (I would not mind a hacky solution) to get this working with the SOS Importer at this time? 

If not, this would be a very handy feature I would love to seen in a future release! One option could be a new element for a `<Token>` in `<SOSMetadata>`.

**Comment by EHJ-52n** [comment]
Hi,
I think that this is linked #73 _Provide basic authentication for secure SOS_.

@glegal: can you give any updates on this issue?
